"""create mix_songs table

Revision ID: 0a59afbf7705
Revises: 931e312c7280
Create Date: 2025-08-13 19:42:15.911543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a59afbf7705'
down_revision = '931e312c7280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mix_songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mix_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mix_id'], ['mixes.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mix_songs')
    # ### end Alembic commands ###
